/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/stats/BarChart.vue')['default']
    BaseChart: typeof import('./src/components/stats/BaseChart.vue')['default']
    BookCard: typeof import('./src/components/BookCard.vue')['default']
    BookForm: typeof import('./src/components/BookForm.vue')['default']
    DisplayModeToggle: typeof import('./src/components/DisplayModeToggle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    NetworkSearch: typeof import('./src/components/NetworkSearch.vue')['default']
    PieChart: typeof import('./src/components/stats/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    StatusFilter: typeof import('./src/components/StatusFilter.vue')['default']
    StatusStats: typeof import('./src/components/StatusStats.vue')['default']
    TagList: typeof import('./src/components/TagList.vue')['default']
    TagSelector: typeof import('./src/components/TagSelector.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
