/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BookCard: typeof import('./src/components/BookCard.vue')['default']
    BookForm: typeof import('./src/components/BookForm.vue')['default']
    NetworkSearch: typeof import('./src/components/NetworkSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    StatusFilter: typeof import('./src/components/StatusFilter.vue')['default']
    StatusStats: typeof import('./src/components/StatusStats.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
